name: Python App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install flake8 autopep8

    - name: Run flake8
      run: flake8 .

    - name: Auto-fix issues with autopep8
      run: autopep8 --in-place --aggressive --aggressive --recursive .

    - name: Commit and Push changes
      run: |
        echo "Checking for changes after autopep8..."
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add .
        if ! git diff --cached --exit-code; then
          git commit -m "Auto-fix linting issues with autopep8"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }} HEAD:main
        else
          echo "No changes to commit."
