name: Python Linting Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 autopep8

    - name: Run flake8 to check for linting issues
      run: |
        echo "Running flake8 to check for linting issues..."
        flake8 . || true

    - name: Auto-fix issues with autopep8
      run: |
        echo "Running autopep8 to fix linting issues..."
        autopep8 --in-place --recursive --aggressive --aggressive .

    - name: Re-run flake8 to verify
      run: |
        echo "Re-checking with flake8 after fixes..."
        flake8 . || true

    - name: Commit and push fixes (if any)
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Checking for changes after autopep8..."
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add .
        if ! git diff --cached --exit-code; then
          git commit -m "Auto-fix linting issues with autopep8"
          git push
        else
          echo "No changes to commit."
        fi
